import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Best IELTS Preparation Course by Munzereen Shahid[2025]",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  },
  themeColor:[
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
